#!/bin/bash
# This utility build the source.changes file and send it to the launchpad server.

# Checks
if [ ! -f debian/control ]; then
    echo "debian/control not found"
    exit 1
fi

if [ ! -x /usr/bin/dpkg-buildpackage ]; then
    echo "dpkg-buildpackage not found"
    exit 1
fi

if [ ! -x /usr/bin/dpkg ]; then
    echo "dpkg not found"
    exit 1
fi

if [ "$1" == "--repo" ]; then
    REPO=$2
else
    REPO="testing"
fi

# Vars
VERSION=$(cat VERSION)
PACKAGE=$(grep Package debian/control | cut -d' ' -f2)

# Build
debuild -S

# Send
dput ppa:vanilla-os/${REPO} ../${PACKAGE}_${VERSION}_source.changes
